var mongoose=require("mongoose");
const product_schema=mongoose.Schema({
	categoryName:{
		type:String,
		required:true
	},
	categoryId:{
		type:String,
		required:true
	},
	categoryDescription:{
		type:String,
		required:true
	},
	categoryImage:{
		type:String,
		required:true
	},
	subCategory:[{
		name:{
			type:String,
			required:true
		},
		id:{
			type:String,
			required:true
		},
		productsList:[
			{
				id:{
					type:String,
					required:true
				},
				name:{
					type:String,
					required:true
				},
				imagepath:{
					type:String,
					required:true
				},
				isFeatured:{
					type:Boolean,
					required:true,
					default:false
				},
				price:{
					type:String,
					required:true
				},
				stock:{
					type:String,
					required:true
				},
				description:[
					{
						title:{
							type:String,
							required:false
						},
						content:{
							type:String,
							required:false
						}
					}
				]
			}
		]
	}]    
});
module.exports= mongoose.model("products" , product_schema);